// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","parentId":"1","id":"2"},"3":{"path":"ner","parentId":"1","id":"3"},"4":{"path":"docs","parentId":"1","id":"4"},"5":{"path":"std","parentId":"1","id":"5"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__layout" */'@/layouts/layout.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__ner" */'@/pages/ner.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__docs" */'@/pages/docs.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__std" */'@/pages/std.tsx')),
},
  };
}
